### PR TITLE
Merge Quickstart Dashboard

### PR DESCRIPTION
**Pull request by cohix**
I'm submitting this PR at the request of @joshbetz to make future PRs involving QS sync more manageable.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Did you fix the performance issues of QS Sync?

**Comment by cohix** [comment]
Starting today, that is my focus. I'm working under josh on the VIP team, and we have a plan to get it fixed up. 



Cheers
Connor Hicks

**Comment by westonruter** [comment]
See also the comments on the previous pull request which was closed last year: #251

**Comment by cohix** [comment]
@westonruter I've reviewed that, our planned changes will fix those issues. This PR is simply to make future changes easier to manage.

**Comment by danielbachhuber** [comment]
I might suggest that the implementation deserves some discussion between the VIP team and VIP developers, as I'm sure @westonruter has implementation suggestions as do I. I think SQL syncing is nasty, and not the direction to head in.

I started a similar project called Dictator that works well for what it does: https://github.com/danielbachhuber/dictator

The primary blocker to moving Dictator forward was lack of reasonable schemas for core data models, which is being solved by WP-API right now.

**Comment by joshbetz** [comment]
Closing. Most of this is not ready to be merged yet.

**Pull request closed without merging**
