### PR TITLE
Adds support for oEmbed provider Wistia

### PR DESCRIPTION
**Pull request by developdaly**
Supported by WordPress.com:
https://en.support.wordpress.com/videos/wistia/

### CODE REVIEW

**Comment by joshbetz** [comment]
@developdaly Thanks. The actual regex is `#https?://[^.]+\.(wistia\.com|wi\.st)/(medias|embed)/.*#`. For the sake of consistency, it would probably be better to use this. If you're able to update the PR, I can go ahead and merge.

**Comment by developdaly** [comment]
@joshbetz All set!

**Comment by joshbetz** [comment]
Awesome, thanks.

**Comment by kraftbj** [comment]
Any reason not to include this into Jetpack?

**Comment by joshbetz** [comment]
@kraftbj Yes, pls :) Would love to have all the oembed providers in Jetpack.

**Pull request merged**
